name = "pdl"
defaultTargets = ["Pdl"]
lintDriver = "batteries/runLinter"

[leanOptions]
weak.linter.mathlibStandardSet = true
# weak.linter.flexible = true  # maybe someday enable this

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.26.0-rc2"

[[lean_lib]]
name = "Pdl"

[[lean_lib]]
name = "Bml"
