name = "pdl"
defaultTargets = ["Pdl"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
weak.linter.mathlibStandardSet = true
weak.linter.flexible = false  # maybe someday enable this
# autoImplicit = false  # maybe someday enable this

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.28.0"

[[lean_lib]]
name = "Pdl"

[[lean_lib]]
name = "Bml"
